<?php

/**
 * @file
 * Contains seo_front.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function seo_front_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the seo_front module.
    case 'help.page.seo_front':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The front page for seo.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function seo_front_theme($existing, $type, $theme, $path) {
  $theme = [];

  //  $theme['page__front'] = [
  //    'template' => 'page--seo-front',
  //    'preprocess functions' => ['seo_front_preprocess_seo_front'],
  //  ];

  return $theme;
}

//
// function seo_front_preprocess_seo_front(&$variables) {
//  $block_manager = \Drupal::service('plugin.manager.block');
//
//  $logo_uri = \Drupal::service('file_system')->copy(drupal_get_path('module', 'seo_front') . '/images/logo.png', 'public://seo-logo.png');
//  $variables['page']['seo_front_logo'] = [
//    '#theme' => 'image',
//    '#uri' => 'public://seo-logo.png',
//    '#alt' => '小旋风SEO_站群软件/蜘蛛池/泛目录「批量建站系统」',
//  ];
//
//  $variables['page']['search'] = $block_manager->createInstance('search_form_block')->build();
//
//  $variables['page']['main_menu'] = $block_manager->createInstance('system_menu_block:main')->build();
//
//  $x = 'a';
// }
//
// **
// * Implements hook_form_FORM_ID_alter() for search_block_form.
// */
// function seo_front_form_search_block_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
//  $form['keys']['#placeholder'] = '请输入关键词, 回车';
// }

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function seo_front_theme_suggestions_views_view_list_alter(array &$suggestions, array $variables) {
//  $view = $variables['view'];
//  if (!empty($view)) {
//    $suggestions[] = '';
//  }
}
