seo_textdata.seo_textdata_type.*:
  type: config_entity
  label: 'Text data type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
