<?php

/**
 * @file
 * Contains seo_negotiator.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function seo_negotiator_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the seo_negotiator module.
    case 'help.page.seo_negotiator':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('域名下主题设置') . '</p>';
      return $output;
    case 'seo_negotiator.theme_list':
      $output = '';
      $output .= '<p>注：未绑定模板的域名将会随机调用，支持泛域名绑定，如: *.abc.com，注：域名必须是对应模型下的才有效</p>';

      return $output;
  }
}
/**
 * Implements hook_sidebar_tee_menu_alter().
 */
function seo_negotiator_sidebar_tee_menu_alter(&$data) {
  $icons = [
    'seo_negotiator.theme_list' => 'gitee-icon icon project',
  ];
  _eabax_core_set_menu_items_icon($data, $icons);
}


/**
 * Implements hook_block_access() 隐藏侧边内容栏.
 */
function seo_negotiator_block_access(\Drupal\block\Entity\Block $block, $operation, \Drupal\Core\Session\AccountInterface $account) {
  if ($operation == 'view') {
    $plugin_id = $block->getPluginId();

    $hide_block = [
      'page_title_block',
      'seo_content_notice_block',
      'views_block:content_recent-block_1',
    ];
    if (in_array($plugin_id, $hide_block)) {
      $route_name = \Drupal::routeMatch()->getRouteName();
      $hide_on = [
        'seo_negotiator.theme_list',
      ];

      if (in_array($route_name, $hide_on)) {
        return \Drupal\Core\Access\AccessResult::forbidden();
      }
    }
    return \Drupal\Core\Access\AccessResult::neutral();
  }
}

/**
 * Implements hook_theme().
 */
function seo_negotiator_theme($existing, $type, $theme, $path) {
  $theme = [];
  $theme['negotiator_theme_form'] = [
    'render element' => 'form',
  ];

  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function seo_negotiator_theme_suggestions_views_view_list_alter(array &$suggestions, array $variables) {
  $view = $variables['view'];
  if (!empty($view)) {
    $suggestions[] = 'views_view_list__' . $view->id();
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for views_view.
 */
function seo_negotiator_theme_suggestions_views_view_alter(array &$suggestions, array $variables) {
  $view = $variables['view'];
  if (!empty($view)) {
    $suggestions[] = 'views_view__' . $view->id();
    if ($view->id() == 'taxonomy_term') {
      $args = $view->args;
      if (is_numeric($args[0])) {
        $suggestions[] = 'views_view__' . $view->id() . '_%';
      }
      $suggestions[] = 'views_view__' . $view->id() . '_' . $args[0];
    }
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function seo_negotiator_theme_suggestions_views_view_unformatted_alter(array &$suggestions, array $variables) {
  $view = $variables['view'];
  if (!empty($view)) {
    $suggestions[] = 'views_view_unformatted__' . $view->id();
    if ($view->id() == 'taxonomy_term') {
      $args = $view->args;
      if (is_numeric($args[0])) {
        $suggestions[] = 'views_view_unformatted__' . $view->id() . '_%';
      }
      $suggestions[] = 'views_view_unformatted__' . $view->id() . '_' . $args[0];
    }
  }
}

/**
 * Implements hook_xmlsitemap_context_info().
 */
function seo_negotiator_xmlsitemap_context_info() {
  $context['domain'] = [
    'label' => '域名',
//    'summary callback' => 'language_name',
    'default' => 'localhost',
  ];
  return $context;
}

/**
 * Implements hook_form_FORM_ID_alter() for xmlsitemap_sitemap_edit_form.
 */
function seo_negotiator_form_xmlsitemap_sitemap_edit_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $options = \Drupal::service('seo_negotiator.manager')->getDynamicDomains();

  $entity = $form_state->getFormObject()->getEntity();

  $domain = '';
  if (!empty($entity->getContext())) {
    $context = $entity->getContext();
    $domain = isset($context['domain']) ? $context['domain'] : '';
  }

  $form['context']['domain'] = [
    '#type' => 'select',
    '#title' => '域名',
    '#options' => $options,
    '#default_value' => $domain,
  ];
}

/**
 * Implements hook_xmlsitemap_context_url_options().
 */
function seo_negotiator_xmlsitemap_context_url_options(array $context) {
  $options = [];

  if (isset($context['domain'])) {
    $options['domain'] = seo_negotiator_domain_load($context['domain']);
    // TODO
    $options['base_url'] = 'http://' . $options['domain'];
  }

  return $options;
}

function seo_negotiator_domain_load($domain = 'localhost') {
  $options = \Drupal::service('seo_negotiator.manager')->getDynamicDomains();

  return isset($options[$domain]) ? $options[$domain] : NULL;
}

// Create xmlsitemap
//$values = [
//  'context' => [
//    'language' => 'zh-hans',
//    'domain' => 'xxxxy',
//  ],
//  'label' => 'xxxxy',
//];
//'id' => xmlsitemap_sitemap_get_context_hash($context);

/**
 * Implements hook_xmlsitemap_context().
 */
function seo_negotiator_xmlsitemap_context() {
  $host = \Drupal::request()->getHost();//getSchemeAndHttpHost();
  $context['domain'] = $host;

  return $context;
}
