<?php

/**
 * @file
 * Contains seo_station_address.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function seo_station_address_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the seo_station_address module.
    case 'help.page.seo_station_address':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('网站提取数据后，生成的地址') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_HOOK() for 设置网站名称.
 */
function seo_station_address_preprocess_page(&$variables) {
  $host = \Drupal::request()->getHost();
  try {
    $storage = \Drupal::entityTypeManager()->getStorage('seo_station_address');
    $entities = $storage->loadByProperties([
      'domain' => $host,
    ]);
    $station_address = reset($entities);
    // 网站名称
    if ($station_address) {
      $variables['wild_web_name'] = [
        '#markup' => $station_address->webname->value,
      ];
      $site_config = \Drupal::configFactory()->getEditable('system.site');
      $site_config->set('name', $station_address->webname->value)->save();
    }

    if (\Drupal::moduleHandler()->moduleExists('seo_logo')) {
      // Get logo
      $storage = \Drupal::entityTypeManager()->getStorage('seo_logo');
      //TODO, 可能影响性能, 待改进
      $logos = $storage->loadMultiple();
      if(!empty($logos)){
        $logo = array_rand($logos, 1);
        if (!empty($logo)) {
          $file = $logos[$logo]->file;
          if (!empty($file->target_id)) {
            $variables['wild_logo'] = ['#markup' => file_create_url($file->entity->getFileUri())];
          }
        }
      }
    }
  }
  catch (\Exception $e) {

  }

}
