<?php

/**
 * @file
 * Contains seo_station_address.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function seo_station_address_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the seo_station_address module.
    case 'help.page.seo_station_address':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('网站提取数据后，生成的地址') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_station_address_process_alter().
 */
function seo_station_address_station_address_process_alter(array $data) {
  $queue = \Drupal::queue('station_address_process');
  $queue->createItem($data);
}

function seo_station_address_page_attachments(array &$attachments) {
  $data = $attachments['#attached']['library'];
  if (!\Drupal::moduleHandler()->moduleExists('devel')) {
    foreach ($data as $key => $item) {
      if ($item == 'contextual/drupal.contextual-links') {
        unset($attachments['#attached']['library'][$key]);
      }
    }
  }
}

/**
 * Implements hook_cron().
 */
function seo_station_address_cron() {
  \Drupal::state()->delete('authorize_redirect_time', 0);
}
