<?php

/**
 * Implements hook_install().
 */
function seo_grant_install($is_syncing) {
  user_role_grant_permissions('authenticated', [
    'view own grant entities',
  ]);

  user_role_grant_permissions('seo', [
    'add seogrant entities',
    'administer seogrant entities',
    'delete seogrant entities',
    'edit seogrant entities',
    'view published seogrant entities',
    'view unpublished seogrant entities',
  ]);
}
