<?php

/**
 * @file
 * Contains dsi_pseudo.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dsi_pseudo_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dsi_pseudo module.
    case 'help.page.dsi_pseudo':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The pseudo machanism') . '</p>';
      return $output;

    default:
  }
}
