spiders.spiders_type.*:
  type: config_entity
  label: 'Spiders type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    source:
      type: string
      label: 来源IPs
    user_agent:
      type: string
      label: UserAgent
